# Setup
title: YouTube Viz
tagline: "A Longitudinal Data Visualization"
description: >-
  A longitudinal data visualization of 96 mio YouTube videos made for
  <a href="https://edu.epfl.ch/coursebook/en/data-visualization-COM-480">COM-480 Data visualization</a>
  at EPFL in Spring 2020. By <a href="https://github.com/lafrimousse">Jonathan Kaeser</a>
  and <a href="https://github.com/tvaucher">Timoté Vaucher</a>.
url: https://tvaucher.github.io
baseurl: /youtube-viz
# paginate: 5
permalink: pretty

# About/contact
author:
  name_1: Timoté Vaucher
  email_1: timote.vaucher@epfl.ch
  name_2: Jonathan Kaeser
  email_2: jonathan.kaeser@epfl.ch

# Gems
plugins:
  #  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"

# Extra vars
version: "0.0.1"
